version: '3'


services:
  db:
    image: postgres
    restart: always
    ports:
      - "36082:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: shop
    volumes:
      - ./postgres:/var/lib/postgresql/data

